### ISSUE TITLE
Convert ERD to tables in Database

### ISSUE THREAD

**Issue by AnisaHMohamed** [AnisaHMohamed/schoodle#1]
Use draw.io

**Comment by dbeattie** [comment]
Alter index.ejs in views to render a home page  (/) based on the wireframe mockup in google doc (https://docs.google.com/document/d/1drL-y1kzS11aP-bptY4VFmkTzxue-HyOUHH4bHT5bDc/edit?usp=sharing)

**Comment by dbeattie** [comment]
#2, #3, #4, and #5 are the more specific table issues.
